// packages/conformance/fixtures/witness/react/src/Button.tsx
import { forwardRef, useImperativeHandle } from 'react';
import type { PressEvent } from '@acme/react';

interface ButtonProps {
  /** Visual variant of the button. */
  variant?: 'primary' | 'secondary';
  /** Disables interaction. */
  disabled?: boolean;
}

interface ButtonHandle {
  focus(): void;
}

/**
 * A themable action button as a JSX function component.
 * @fires {PressEvent} press - Fired on activation via pointer or keyboard.
 * @slot - Button label content (children).
 * @slot icon - Leading icon element.
 * @cssprop {<length>} [--acme-button-radius=4px] - Corner radius of the button.
 */
export const Button = forwardRef<ButtonHandle, ButtonProps>(
  ({ variant = 'primary', disabled = false }, ref) => {
    useImperativeHandle(ref, () => ({
      /** Moves keyboard focus to the button via the imperative handle. */
      focus(): void {},
    }));
    return <button className={variant} disabled={disabled} />;
  },
);

// examples/nx-angular-testbed/libs/ui/src/lib/button/button.ts
import { Component, input, output } from '@angular/core';

/**
 * Triggers a single action when activated.
 * @slot - Default label content.
 * @slot icon - Leading icon rendered before the label (ng-content select="[icon]").
 */
@Component({
  selector: 'tb-button',
  template: `
    <button [class]="'tb-button tb-button--' + variant() + ' tb-button--' + size()" [disabled]="disabled()" (click)="press.emit($event)">
      <ng-content select="[icon]"></ng-content>
      <ng-content></ng-content>
    </button>
  `,
  styleUrl: './button.css',
})
export class Button {
  /** Visual style of the button. */
  variant = input<'primary' | 'secondary' | 'ghost'>('primary');

  /** Size of the button. */
  size = input<'small' | 'medium' | 'large'>('medium');

  /** Whether the button is disabled. */
  disabled = input<boolean>(false);

  /** Fired when the button is activated by pointer or keyboard. */
  press = output<MouseEvent>();
}
