// examples/vite-react-testbed/libs/ui/src/lib/alert.tsx
import type { ReactNode } from 'react';
import type { StatusTone, SurfaceBase, WithChildren } from './props.js';

interface AlertProps extends SurfaceBase, WithChildren {
  /** Severity of the alert. */
  type?: StatusTone;
  /** Whether a dismiss control is shown. */
  dismissible?: boolean;
  /** Called when the alert is dismissed via its dismiss control. */
  onDismiss?: () => void;
}

/**
 * Displays a prominent message about status or a required action.
 * @acmSemantic alert - Announces an important message in place; does not steal focus.
 * @slot actions - Action buttons shown alongside the message.
 * @cssprop {<color>} [--tb-alert-accent=#06c] - Accent colour of the leading rule.
 * @example Dismissible error
 * ```tsx
 * const failed = (
 *   <Alert type="error" dismissible onDismiss={() => console.log('dismissed')}>
 *     Could not save your changes.
 *   </Alert>
 * );
 * ```
 */
export function Alert({ type = 'info', dismissible = false, children }: AlertProps): ReactNode {
  return (
    <div className={`tb-alert tb-alert--${type}`} role="alert">
      {children}
      {dismissible ? <button type="button">&times;</button> : null}
    </div>
  );
}

// examples/nx-angular-testbed/libs/ui/src/lib/alert/alert.ts
import { Component, input, output } from '@angular/core';

/**
 * Displays a prominent message about status or a required action.
 * @acmSemantic alert - Announces an important message in place; does not steal focus.
 * @slot - Default message content.
 * @slot actions - Action buttons shown alongside the message (ng-content select="[actions]").
 * @example Dismissible error with actions
 * ```html
 * <tb-alert type="error" [dismissible]="true" (dismissed)="onDismiss()">
 *   Could not save your changes.
 *   <tb-button actions variant="ghost">Retry</tb-button>
 * </tb-alert>
 * ```
 */
@Component({
  selector: 'tb-alert',
  template: `
    <div [class]="'tb-alert tb-alert--' + type()">
      <ng-content></ng-content>
      <ng-content select="[actions]"></ng-content>
      @if (dismissible()) {
        <button type="button" (click)="dismissed.emit()">&times;</button>
      }
    </div>
  `,
  styleUrl: './alert.css',
})
export class Alert {
  /** Severity of the alert. */
  type = input<'info' | 'success' | 'warning' | 'error'>('info');

  /** Whether a dismiss control is shown. */
  dismissible = input<boolean>(false);

  /** Fired when the alert is dismissed via its dismiss control. */
  dismissed = output<void>();
}
