// examples/vite-react-testbed/libs/ui/src/lib/spinner.tsx
import type { ReactNode } from 'react';
import type { ControlSize, SurfaceBase } from './props.js';

interface SpinnerProps extends SurfaceBase {
  /** Size of the spinner. */
  size?: ControlSize;
  /** Text announced to assistive technology while the spinner is visible. */
  label?: string;
}

/**
 * Indicates that work is in progress and its duration is unknown.
 * @acmSemantic progressbar - Indeterminate progress; use a determinate meter when a percentage is known.
 * @cssprop {<color>} [--tb-spinner-color=currentColor] - Stroke colour of the spinner.
 * @example Inline loading state
 * ```tsx
 * const busy = <Spinner size="small" label="Loading results" />;
 * ```
 */
export function Spinner({ size = 'medium', label = 'Loading' }: SpinnerProps): ReactNode {
  return <span className={`tb-spinner tb-spinner--${size}`} role="status" aria-label={label} />;
}

// examples/nx-angular-testbed/libs/ui/src/lib/spinner/spinner.ts
import { Component, input } from '@angular/core';

/**
 * An indeterminate loading indicator.
 * @acmSemantic progressbar - Indeterminate progress; use a determinate meter when a percentage is known.
 * @example Inline loading state
 * ```html
 * <tb-spinner size="small" label="Loading results"></tb-spinner>
 * ```
 */
@Component({
  selector: 'tb-spinner',
  template: `<span role="status" [class]="'tb-spinner tb-spinner--' + size()" [attr.aria-label]="label()"></span>`,
})
export class Spinner {
  /** Diameter of the spinner. */
  size = input<'small' | 'medium' | 'large'>('medium');

  /** Accessible label describing what is loading. */
  label = input<string>('Loading');
}
