// packages/conformance/fixtures/analyzer/angular/src/acme-button.component.ts
import { Component, input, model, output } from '@angular/core';
import type { PressEvent } from './events.js';

/**
 * A themable action button with signal inputs and two-way binding.
 * @slot - Button label content (default ng-content).
 * @slot icon - Leading icon (ng-content select="[icon]").
 * @cssprop {<length>} [--acme-button-radius=4px] - Corner radius of the button.
 */
@Component({
  selector: 'acme-button',
  template: '<button><ng-content></ng-content></button>',
})
export class AcmeButtonComponent {
  /** Visual variant of the button (signal input). */
  variant = input<'primary' | 'secondary'>('primary');

  /** Toggle state; supports [(pressed)] two-way binding. */
  pressed = model<boolean>(false);

  /** Fired on activation via pointer or keyboard. */
  press = output<PressEvent>();

  /** Internal render latch; not part of the public API. */
  private _armed = false;

  /** Moves keyboard focus to the button. */
  focus(): void {
    this._armed = true;
  }

  ngOnInit(): void {}
}

// packages/conformance/fixtures/analyzer/stencil/src/acme-button.tsx
import { Component, Prop, Event, EventEmitter, Method, State, h } from '@stencil/core';
import type { PressEvent } from './events';

/**
 * A themable action button rendered as a custom element.
 * @slot - Button label content.
 * @slot icon - Leading icon.
 * @cssprop {<length>} [--acme-button-radius=4px] - Corner radius of the button.
 * @csspart label - The label span inside the shadow root.
 */
@Component({ tag: 'acme-button', shadow: true })
export class AcmeButton {
  /** Visual variant of the button. */
  @Prop() variant: 'primary' | 'secondary' = 'primary';

  /** Disables pointer and keyboard interaction; reflected to an attribute. */
  @Prop({ reflect: true }) disabled: boolean = false;

  /** Fired on activation via pointer or keyboard. */
  @Event() press!: EventEmitter<PressEvent>;

  /** Internal pressed latch; not part of the public API. */
  @State() private armed: boolean = false;

  /** Moves keyboard focus to the button. */
  @Method()
  async setFocus(): Promise<void> {
    this.armed = true;
  }

  render() {
    return (
      <button>
        <slot />
      </button>
    );
  }
}
