// examples/vite-react-testbed/libs/ui/src/lib/checkbox.tsx
import type { ReactNode } from 'react';
import type { FieldBase } from './props.js';

interface CheckboxProps extends FieldBase {
  /** Whether the box is ticked. */
  checked?: boolean;
  /** Whether the box shows the mixed state. */
  indeterminate?: boolean;
  /** Called with the new checked state when the box is toggled. */
  onCheckedChange?: (checked: boolean) => void;
}

/**
 * A single on/off choice.
 * @acmSemantic checkbox - One independent on/off choice; use a radio group for exclusive choices.
 * @example Consent checkbox
 * ```tsx
 * const consent = (
 *   <Checkbox label="Email me receipts" required onCheckedChange={(on) => console.log(on)} />
 * );
 * ```
 * @example Mixed "select all" state
 * ```tsx
 * const selectAll = <Checkbox label="Select all" indeterminate />;
 * ```
 */
export function Checkbox({
  checked = false,
  indeterminate = false,
  disabled = false,
  label,
}: CheckboxProps): ReactNode {
  return (
    <label className="tb-checkbox">
      <input
        type="checkbox"
        checked={checked}
        disabled={disabled}
        data-indeterminate={indeterminate}
      />
      {label}
    </label>
  );
}

// examples/nx-angular-testbed/libs/ui/src/lib/checkbox/checkbox.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

/**
 * A checkable input for a binary choice.
 * @acmSemantic checkbox - One independent on/off choice; use a radio group for exclusive choices.
 * @slot label - Label content shown next to the checkbox (ng-content select="[label]").
 * @example Bound checked state
 * ```html
 * <tb-checkbox [checked]="consent" (changed)="consent = $event">
 *   <span label>Email me receipts</span>
 * </tb-checkbox>
 * ```
 */
@Component({
  selector: 'tb-checkbox',
  template: `
    <label class="tb-checkbox">
      <input
        type="checkbox"
        [checked]="checked"
        [disabled]="disabled"
        (change)="changed.emit($any($event.target).checked)"
      />
      <ng-content select="[label]"></ng-content>
    </label>
  `,
  styleUrl: './checkbox.css',
})
export class Checkbox {
  /** Whether the checkbox is checked. */
  @Input() checked = false;

  /** Whether the checkbox is disabled. */
  @Input() disabled = false;

  /** Fired with the new checked state when the checkbox is toggled. */
  @Output() changed = new EventEmitter<boolean>();
}
