// packages/conformance/fixtures/witness/lit/src/acme-button.ts
import { LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { PressEvent } from '@acme/wc';

/**
 * A themable action button rendered as a custom element.
 * @fires {PressEvent} press - Fired on activation via pointer or keyboard.
 * @slot - Button label content.
 * @slot icon - Leading icon.
 * @cssprop {<length>} [--acme-button-radius=4px] - Corner radius of the button.
 * @csspart label - The label span inside the shadow root.
 */
@customElement('acme-button')
export class AcmeButton extends LitElement {
  /** Visual variant of the button. */
  @property() variant: 'primary' | 'secondary' = 'primary';

  /** Disables pointer and keyboard interaction. */
  @property({ reflect: true }) disabled: boolean = false;

  /** Moves keyboard focus to the button. */
  focus(options: FocusOptions): void {
    super.focus(options);
  }
}

// packages/conformance/fixtures/witness/angular/src/acme-button.component.ts
import { Component, input, model, output } from '@angular/core';
import type { PressEvent } from '@acme/ng';

/**
 * A themable action button with signal inputs and two-way binding.
 * @slot - Button label content (default ng-content).
 * @slot icon - Leading icon (ng-content select="[icon]").
 * @cssprop {<length>} [--acme-button-radius=4px] - Corner radius of the button.
 */
@Component({
  selector: 'acme-button',
  standalone: true,
  template:
    '<button><ng-content></ng-content><ng-content select="[icon]"></ng-content></button>',
})
export class AcmeButtonComponent {
  /** Visual variant of the button (signal input). */
  variant = input<'primary' | 'secondary'>('primary');

  /** Toggle state; supports [(pressed)] two-way binding. */
  pressed = model<boolean>(false);

  /** Fired on activation via pointer or keyboard. */
  press = output<PressEvent>();

  /** Moves keyboard focus to the button. */
  focus(): void {}
}
