// examples/nx-angular-testbed/libs/ui/src/lib/avatar/avatar.ts
import { Component, input } from '@angular/core';

/**
 * A round image representing a user or entity.
 * @acmSemantic avatar - Identifies a person or entity; `alt` is the accessible name.
 * @slot - Fallback content shown when no image is available (e.g. initials).
 * @example Image with initials fallback
 * ```html
 * <tb-avatar src="/ada.png" alt="Ada Lovelace" size="large">AL</tb-avatar>
 * ```
 */
@Component({
  selector: 'tb-avatar',
  template: `
    @if (src()) {
      <img [class]="'tb-avatar tb-avatar--' + size()" [src]="src()" [alt]="alt()" />
    } @else {
      <span [class]="'tb-avatar tb-avatar--' + size()"><ng-content></ng-content></span>
    }
  `,
})
export class Avatar {
  /** Image URL; when absent, the projected fallback content is shown. */
  src = input<string>('');

  /** Accessible alt text for the image. */
  alt = input<string>('');

  /** Diameter of the avatar. */
  size = input<'small' | 'medium' | 'large'>('medium');
}

// examples/vite-react-testbed/libs/ui/src/lib/avatar.tsx
import type { ReactNode } from 'react';
import type { ControlSize, SurfaceBase } from './props.js';

interface AvatarProps extends SurfaceBase {
  /** Image source; falls back to initials when absent. */
  src?: string;
  /** Accessible name for the depicted person or entity. */
  name: string;
  /** Size of the avatar. */
  size?: ControlSize;
  /** Shape of the avatar. */
  shape?: 'circle' | 'square';
}

/**
 * Represents a person or entity as an image or initials.
 * @acmSemantic avatar - Identifies a person or entity; `name` is the accessible name.
 * @example Image with initials fallback
 * ```tsx
 * const who = <Avatar name="Ada Lovelace" src="/ada.png" size="large" shape="circle" />;
 * ```
 */
export function Avatar({ size = 'medium', shape = 'circle', src, name }: AvatarProps): ReactNode {
  return src ? (
    <img className={`tb-avatar tb-avatar--${size} is-${shape}`} src={src} alt={name} />
  ) : (
    <span className={`tb-avatar tb-avatar--${size} is-${shape}`}>{name.slice(0, 2)}</span>
  );
}
