// examples/nx-angular-testbed/libs/ui/src/lib/badge/badge.ts
import { Component, Input } from '@angular/core';

/**
 * A compact label used to display status or a count.
 * @acmSemantic badge - Annotates a nearby element with a count or status; never interactive.
 * @slot - Default content shown inside the badge.
 * @example Status tone
 * ```html
 * <tb-badge tone="success">Shipped</tb-badge>
 * ```
 */
@Component({
  selector: 'tb-badge',
  template: `<span [class]="'tb-badge tb-badge--' + tone"><ng-content></ng-content></span>`,
})
export class Badge {
  /** Visual tone of the badge. */
  @Input() tone: 'neutral' | 'info' | 'success' | 'warning' | 'danger' = 'neutral';

  /** Text label, used when no content is projected. */
  @Input() label = '';
}

// examples/vite-react-testbed/libs/ui/src/lib/badge.tsx
import type { ReactNode } from 'react';
import type { StatusTone, SurfaceBase, WithChildren } from './props.js';

interface BadgeProps extends SurfaceBase, WithChildren {
  /** Colour of the badge. */
  tone?: StatusTone | 'neutral';
  /** Whether the badge renders as a filled pill rather than an outline. */
  solid?: boolean;
}

/**
 * A compact count or status marker attached to another element.
 * @acmSemantic badge - Annotates a nearby element with a count or status; never interactive.
 * @example Status marker
 * ```tsx
 * const shipped = <Badge tone="success" solid>Shipped</Badge>;
 * ```
 */
export function Badge({ tone = 'neutral', solid = false, children }: BadgeProps): ReactNode {
  return <span className={`tb-badge tb-badge--${tone}${solid ? ' is-solid' : ''}`}>{children}</span>;
}
