// examples/nx-angular-testbed/libs/ui/src/lib/card/card.ts
import { Component, input } from '@angular/core';

/**
 * A container that groups related content with an optional header and footer.
 * @acmSemantic card - Groups related content as one unit.
 * @slot - Default body content.
 * @slot header - Header content shown above the body (ng-content select="[header]").
 * @slot footer - Footer content shown below the body (ng-content select="[footer]").
 * @example Header, body, and footer
 * ```html
 * <tb-card [elevation]="2">
 *   <h3 header>Invoice #1042</h3>
 *   Due in 14 days.
 *   <tb-button footer variant="primary">Pay now</tb-button>
 * </tb-card>
 * ```
 */
@Component({
  selector: 'tb-card',
  template: `
    <div [class]="'tb-card tb-card--elevation-' + elevation()">
      <div part="header"><ng-content select="[header]"></ng-content></div>
      <div part="body"><ng-content></ng-content></div>
      <div part="footer"><ng-content select="[footer]"></ng-content></div>
    </div>
  `,
  styleUrl: './card.css',
})
export class Card {
  /** Shadow depth, from 0 (flat) to 3 (raised). */
  elevation = input<0 | 1 | 2 | 3>(1);
}

// examples/vite-react-testbed/libs/ui/src/lib/card.tsx
import type { ReactNode } from 'react';
import type { SurfaceBase, WithChildren } from './props.js';

interface CardProps extends SurfaceBase, WithChildren {
  /** Heading shown at the top of the card. */
  title?: string;
  /** Elevation step, 0–3; higher casts a deeper shadow. */
  elevation?: number;
  /** Whether the card responds to pointer interaction. */
  interactive?: boolean;
}

/**
 * Groups related content on a raised surface.
 * @acmSemantic card - Groups related content as one unit; the title names the group.
 * @slot header - Replaces the default title row.
 * @slot footer - Actions shown at the bottom of the card.
 * @cssprop {<length>} [--tb-card-radius=8px] - Corner radius of the card.
 * @csspart body - The card's content region.
 * @example Interactive summary card
 * ```tsx
 * const summary = (
 *   <Card title="Invoice #1042" elevation={2} interactive>
 *     Due in 14 days.
 *   </Card>
 * );
 * ```
 */
export function Card({ elevation = 1, interactive = false, title, children }: CardProps): ReactNode {
  return (
    <section className={`tb-card tb-card--e${elevation}`} data-interactive={interactive}>
      {title ? <h3>{title}</h3> : null}
      <div part="body">{children}</div>
    </section>
  );
}
