// examples/nx-angular-testbed/libs/ui/src/lib/tooltip/tooltip.ts
import { Component, input } from '@angular/core';

/**
 * Shows a short message near an element on hover or focus.
 * @acmSemantic tooltip - Supplementary label for its trigger; never the only source of information.
 * @slot - Element that triggers the tooltip on hover or focus.
 * @example Wrapping a trigger
 * ```html
 * <tb-tooltip text="Deletes the invoice permanently" placement="right">
 *   <tb-button variant="ghost">Delete</tb-button>
 * </tb-tooltip>
 * ```
 */
@Component({
  selector: 'tb-tooltip',
  template: `
    <span class="tb-tooltip" [attr.data-placement]="placement()" [attr.title]="text()">
      <ng-content></ng-content>
    </span>
  `,
})
export class Tooltip {
  /** Message shown in the tooltip. */
  text = input<string>('');

  /** Preferred side of the trigger element to render the tooltip. */
  placement = input<'top' | 'right' | 'bottom' | 'left'>('top');
}

// examples/vite-react-testbed/libs/ui/src/lib/tooltip.tsx
import type { ReactNode } from 'react';
import type { SurfaceBase, WithChildren } from './props.js';

interface TooltipProps extends SurfaceBase, WithChildren {
  /** Text shown in the tooltip bubble. */
  content: string;
  /** Preferred side of the trigger to render on. */
  placement?: 'top' | 'right' | 'bottom' | 'left';
  /** Delay before the tooltip appears, in milliseconds. */
  openDelay?: number;
}

/**
 * Shows a short explanatory label when its trigger is hovered or focused.
 * @acmSemantic tooltip - Supplementary label for its trigger; never the only source of information.
 * @example Wrapping a trigger
 * ```tsx
 * const hint = (
 *   <Tooltip content="Deletes the invoice permanently" placement="right" openDelay={400}>
 *     Delete
 *   </Tooltip>
 * );
 * ```
 */
export function Tooltip({
  placement = 'top',
  openDelay = 200,
  content,
  children,
}: TooltipProps): ReactNode {
  return (
    <span className={`tb-tooltip tb-tooltip--${placement}`} data-delay={openDelay} title={content}>
      {children}
    </span>
  );
}
